### ISSUE TITLE
Modify License Header

### ISSUE THREAD

**Issue by codenamewei** [CertifaiAI/TrainingLabs#120]
for files created before 2020

* Copyright (c) 2019 Skymind Holdings Bhd.
* Copyright (c) 2020 CertifAI Sdn. Bhd.

for files created 2020 onwards

* Copyright (c) 2020 CertifAI Sdn. Bhd.

**Comment by codenamewei** [comment]
@KianYang-Lee do a quick search throughout all existing files and make sure this is comply.

do a PR only with these changes.

**Comment by KianYang-Lee** [comment]
Dear @codenamewei will definitely work on this. May I know the deadline for this?

**Comment by codenamewei** [comment]
@KianYang-Lee within this week, thank you.
