### ISSUE TITLE
 j < nimages in function 'cv::histPrepareImages for package ai.certifai.solution.image_processing.HistogramEqualization.java

### ISSUE THREAD

**Issue by KianYang-Lee** [CertifaiAI/TrainingLabs#147]
**Describe the bug**
When run, this error occurred.
```
opencv-4.3.0\modules\imgproc\src\histogram.cpp:160: error: (-215:Assertion failed) j < nimages in function 'cv::histPrepareImages
```

**Screenshots**
![image](https://user-images.githubusercontent.com/49669630/108968112-51e73180-76bb-11eb-882d-96f1c5d6395d.png)

**Additional context**
Also noticed the outdated import line. Will open a branch to fix this when schedule is less packed.

**Comment by jacklynlxq** [comment]
It seems to be the problem with the dimension / number of channels.

Not sure if it'd work on your machine but I managed to eliminate the error by changing this line
```private IntPointer channels = new IntPointer(3);```
to
```int[] channels_arr = new int[]{0, 1, 2};```
```private IntPointer channels = new IntPointer(channels_arr);```

I am not sure what is the reason behind it but you can look into the source code and maybe there's a better workaround: https://github.com/bytedeco/javacpp/blob/f8e91858655cebbc673f9c07303ad324b813427f/src/main/java/org/bytedeco/javacpp/IntPointer.java#L62

Ref: https://github.com/bytedeco/javacv-examples/blob/master/OpenCV_Cookbook/src/test/java/opencv_cookbook/CalcHistTest.java

**Comment by KianYang-Lee** [comment]
Thanks! It works wonderfully! will update it in the patch
