### ISSUE TITLE
README link broken

### ISSUE THREAD

**Issue by chiaweilim** [CertifaiAI/TrainingLabs#66]
A few I tried which is not working. Did not go through all of them

![readme](https://user-images.githubusercontent.com/48112813/82040871-d8f18d00-96d9-11ea-9826-e213bb6e5be2.png)

**Comment by chiaweilim** [comment]
Most links were broken. Check and update thoroughly

**Comment by chiaweilim** [comment]
update java install link to here. https://adoptopenjdk.net/
ask me why if you are not clear

**Comment by chooneung** [comment]
#90 
fixed and updated broken links, and reformatted projects showcase into folder-based.

**Comment by kenghooi-teoh** [comment]
fixed in https://github.com/CertifaiAI/TrainingLabs/pull/90
