### ISSUE TITLE
License header missing / ill written

### ISSUE THREAD

**Issue by chiaweilim** [CertifaiAI/TrainingLabs#80]
Each java program should have header like this
https://gist.github.com/chiaweilim/c4c468d6a3f9112a12ac1461ec13d3a7

The formatting of this is bad from copy and pasting it. 
https://github.com/CertifaiAI/TrainingLabs/blob/master/dl4j-labs/src/main/java/global/skymind/solution/convolution/objectdetection/WebCamObjectDetection.java

This file is missing license header
https://github.com/CertifaiAI/TrainingLabs/blob/master/dl4j-labs/src/main/java/global/skymind/solution/convolution/objectdetection/ImageObjectDetection.java

Go through all the files and make sure the header is added correctly.

**Comment by kenghooi-teoh** [comment]
fixed in https://github.com/CertifaiAI/TrainingLabs/pull/86 by @alvin9964
